### ISSUE TITLE
Incorrect Instructions

### ISSUE THREAD

**Issue by tonytonyistony** [WolfBearGames/Godot-GeolocationPlugin-Android#1]
The instructions listed in the git do not match the files provided.

> Put the Geolocation-Plugin Folder (containing the .aar and .gdap file) in the res://android/plugins folder in your project

1. There is no folder inside the project zip named "Geolocation-Plugin"
2. There is no .gdap file inside the project zip.

Am I missing something?

**Comment by WolfBearGames** [comment]
Thank you. There was an error in the instruction. You must put the .aar and .gdap directly files into the android/plugins folder (they should not be in another subfolder).

1. The Release zip file "[GodotGeolocationPluginAndroid-v1.0.0.zip](https://github.com/WolfBearGames/Godot-GeolocationPlugin-Android/releases/download/v1.0.0/GodotGeolocationPluginAndroid-v1.0.0.zip) is the "Geolocation-Plugin" folder, but as mentioned above you have to put the contents of this folder in the android/plugins folder, not the folder itself.
2. There should be a .gdap file in the mentioned zip file.

You may also have a look at https://github.com/WolfBearGames/GeolocationTestApp where you find a small test app with the plugin already set up. You can browse the repository and see the files and their correct locations.

**Comment by tonytonyistony** [comment]
Thanks for the clarification. I put in a pull request with proposed documentation changes to be more clear.
