### ISSUE TITLE
Update for Godot v4

### ISSUE THREAD

**Issue by tonytonyistony** [WolfBearGames/Godot-GeolocationPlugin-Android#2]
Will this plugin be updated for v4 of Godot?

**Comment by WolfBearGames** [comment]
Probably... I wanted to wait until C# exporting to Android and iOS are available in Godot 4.x.

**Comment by KimPlaybit** [comment]
> Probably... I wanted to wait until C# exporting to Android and iOS are available in Godot 4.x.

"Godot 4.2 now has experimental support for Android (.NET 7.0+ required) and iOS (.NET 8.0 required) export targets. "

see here. https://godotengine.org/article/godot-4-2-arrives-in-style/

**Comment by WolfBearGames** [comment]
I will have a look when I find some spare time.
